/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_QRCODE_DETECT_H
#define PHP_QRCODE_DETECT_H

extern zend_module_entry qrcode_detect_module_entry;
#define phpext_qrcode_detect_ptr &qrcode_detect_module_entry

#ifdef PHP_WIN32
# define PHP_QRCODE_DETECT_API __declspec(dllexport)
#else
# define PHP_QRCODE_DETECT_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(qrcode_detect);
PHP_MSHUTDOWN_FUNCTION(qrcode_detect);
PHP_RINIT_FUNCTION(qrcode_detect);
PHP_RSHUTDOWN_FUNCTION(qrcode_detect);
PHP_MINFO_FUNCTION(qrcode_detect);

ZEND_NAMED_FUNCTION(_wrap_single_detect_file);
ZEND_NAMED_FUNCTION(_wrap_single_detect_memory);
#endif /* PHP_QRCODE_DETECT_H */
