<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('qrcode_detect')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_qrcode_detect.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('qrcode_detect.so')) return;
    } else {
      if (!dl('qrcode_detect.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class qrcode_detect {
	static function single_detect_file($fileName,$REF) {
		return single_detect_file($fileName,&$REF);
	}

	static function single_detect_memory($ptr,$size,$imageType,$REF) {
		return single_detect_memory($ptr,$size,$imageType,&$REF);
	}
}

/* PHP Proxy Classes */

?>
