/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_BARCODE_H
#define PHP_BARCODE_H

extern zend_module_entry barcode_module_entry;
#define phpext_barcode_ptr &barcode_module_entry

#ifdef PHP_WIN32
# define PHP_BARCODE_API __declspec(dllexport)
#else
# define PHP_BARCODE_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(barcode);
PHP_MSHUTDOWN_FUNCTION(barcode);
PHP_RINIT_FUNCTION(barcode);
PHP_RSHUTDOWN_FUNCTION(barcode);
PHP_MINFO_FUNCTION(barcode);

ZEND_NAMED_FUNCTION(_wrap_detect);
#endif /* PHP_BARCODE_H */
